### ISSUE TITLE
Any planned updates for current foundry versions?

### ISSUE THREAD

**Issue by tbrockwood** [HadaIonut/Foundry-LuckForRolls#1]
I'm running Foundry 0.8.9 and with Luck for Rolls running, it throws "actor lacks permission to update ..." errors so long as Luck for Rolls is enabled. I'm thinking it's probably because the module's not built for the newest foundry, so wondering if you had plans to update it?

**Comment by HadaIonut** [comment]
Hello, sadly no. 

Because of the way I have designed this module it requires me to update it for every single Foundry version and that is way more work then it is worth it. 
So I have dropped support for this module. But if anyone in the community is willing to continue work on it I am more then happy to see a fork being made
